# Generated by Django 4.0.2 on 2022-04-24 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('N_Vehicule', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Designation', models.CharField(max_length=300)),
                ('Type', models.CharField(choices=[('Autonome', 'Autonome'), ('Remorque', 'Remorque')], default='Autonome', max_length=50)),
                ('Marque', models.CharField(max_length=300)),
                ('GrandeFamille', models.CharField(choices=[('MAT-TRANSPO', 'MAT-TRANSPO'), ('MAT-EXPLOI', 'MAT-EXPLOI')], default='MAT-TRANSPO', max_length=50)),
                ('Famille', models.CharField(choices=[('REMORQ-SEC', 'REMORQ-SEC'), ('REMORQ-FRAIS', 'REMORQ-FRAIS'), ('CAM-POILOU-SEC', 'CAM-POILOU-SEC'), ('CAM-POILOU-FRAIS', 'CAM-POILOU-FRAIS'), ('CHARIOT-ELEV', 'CHARIOT-ELEV')], default='REMORQ-SEC', max_length=50)),
                ('NombrePalette', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ListeLivraisonFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLivraison', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('camion', models.CharField(max_length=100)),
                ('NumberPalates', models.CharField(max_length=100)),
                ('dateLivraison', models.DateField(null=True)),
                ('type', models.CharField(choices=[('frais', 'frais'), ('sec', 'sec')], default='sec', max_length=300)),
            ],
            options={
                'ordering': ['dateLivraison'],
            },
        ),
        migrations.CreateModel(
            name='ListeLivraisonSec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLivraison', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('camion', models.CharField(max_length=100)),
                ('NumberPalates', models.CharField(max_length=100)),
                ('dateLivraison', models.DateField(null=True)),
                ('type', models.CharField(choices=[('frais', 'frais'), ('sec', 'sec')], default='sec', max_length=300)),
            ],
            options={
                'ordering': ['dateLivraison'],
            },
        ),
        migrations.CreateModel(
            name='Markets',
            fields=[
                ('Code', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('Magasin', models.CharField(max_length=300)),
                ('Longitude', models.CharField(max_length=300)),
                ('Latitude', models.CharField(max_length=300)),
                ('Coordinates', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberPalates', models.CharField(max_length=100)),
                ('Biere', models.CharField(max_length=100, null=True)),
                ('dateLivraison', models.DateField()),
                ('Ville', models.CharField(choices=[('ariana', 'ariana'), ('beja', 'beja'), ('benarous', 'benarous'), ('bizert', 'bizert'), ('gabes', 'gabes'), ('gafsa', 'gafsa'), ('gasrine', 'gasrine'), ('gbeli', 'gbeli'), ('jandouba', 'jandouba'), ('kairawen', 'kairawen'), ('kef', 'kef'), ('mahdia', 'mahdia'), ('manouba', 'manouba'), ('mednine', 'mednine'), ('monastir', 'monastir'), ('nabeul', 'nabeul'), ('seliana', 'seliana'), ('sfax', 'sfax'), ('sidi-bouzid', 'sidi-bouzid'), ('sousse', 'sousse'), ('tatawin', 'tatawin'), ('tozeur', 'tozeur'), ('zaghwen', 'zaghwen')], default='sfax', max_length=300)),
                ('type', models.CharField(choices=[('frais', 'frais'), ('sec', 'sec')], default='sec', max_length=300)),
                ('Destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crrefourplatforme.markets')),
            ],
            options={
                'ordering': ['dateLivraison'],
            },
        ),
        migrations.CreateModel(
            name='chauffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('dateNaissance', models.DateField()),
                ('password', models.CharField(max_length=100, null=True)),
                ('matricule', models.CharField(max_length=100, null=True)),
                ('nbkilometrage', models.CharField(max_length=100, null=True)),
                ('camion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crrefourplatforme.camion')),
            ],
            options={
                'ordering': ['dateNaissance'],
            },
        ),
    ]
