# Generated by Django 4.0.2 on 2022-04-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listelivraisonfrais',
            name='etat',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('-1', '-1')], default='-1', max_length=300),
        ),
        migrations.AddField(
            model_name='listelivraisonsec',
            name='etat',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('-1', '-1')], default='-1', max_length=300),
        ),
        migrations.AddField(
            model_name='livraison',
            name='etat',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('-1', '-1')], default='-1', max_length=300),
        ),
    ]
