# Generated by Django 4.0.2 on 2022-04-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0002_listelivraisonfrais_etat_listelivraisonsec_etat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listelivraisonfrais',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
