# Generated by Django 4.0.2 on 2022-04-25 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0003_alter_listelivraisonfrais_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listelivraisonfrais',
            old_name='id',
            new_name='idL',
        ),
    ]
