# Generated by Django 4.0.2 on 2022-04-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0004_rename_id_listelivraisonfrais_idl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listelivraisonfrais',
            old_name='idL',
            new_name='id',
        ),
    ]
