# Generated by Django 4.0.2 on 2022-04-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0005_rename_idl_listelivraisonfrais_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='enpanne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='Ville',
            field=models.CharField(choices=[('tunis', 'tunis'), ('ariana', 'ariana'), ('beja', 'beja'), ('benarous', 'benarous'), ('bizert', 'bizert'), ('gabes', 'gabes'), ('gafsa', 'gafsa'), ('gasrine', 'gasrine'), ('gbeli', 'gbeli'), ('jandouba', 'jandouba'), ('kairawen', 'kairawen'), ('kef', 'kef'), ('mahdia', 'mahdia'), ('manouba', 'manouba'), ('mednine', 'mednine'), ('monastir', 'monastir'), ('nabeul', 'nabeul'), ('seliana', 'seliana'), ('sfax', 'sfax'), ('sidi-bouzid', 'sidi-bouzid'), ('sousse', 'sousse'), ('tatawin', 'tatawin'), ('tozeur', 'tozeur'), ('zaghwen', 'zaghwen')], default='sfax', max_length=300),
        ),
    ]
