# Generated by Django 4.0.2 on 2022-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0006_camion_enpanne_alter_livraison_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='enpanne',
        ),
        migrations.AddField(
            model_name='camion',
            name='fonctionnelle',
            field=models.BooleanField(default=True),
        ),
    ]
