# Generated by Django 4.0.2 on 2022-04-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0009_alter_listelivraisonfrais_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='listelivraisonfrais',
            name='nbPalet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listelivraisonfrais',
            name='taux',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listelivraisonsec',
            name='nbPalet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listelivraisonsec',
            name='taux',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
