# Generated by Django 4.0.2 on 2022-04-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0010_listelivraisonfrais_nbpalet_listelivraisonfrais_taux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listelivraisonfrais',
            name='etat',
            field=models.CharField(choices=[('terminer', 'terminer'), ('en cours', 'en cours'), ('enpanne', 'enpanne')], default='en cours', max_length=300),
        ),
        migrations.AlterField(
            model_name='listelivraisonsec',
            name='etat',
            field=models.CharField(choices=[('terminer', 'terminer'), ('en cours', 'en cours'), ('enpanne', 'enpanne')], default='en cours', max_length=300),
        ),
    ]
