# Generated by Django 4.0.2 on 2022-04-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crrefourplatforme', '0011_alter_listelivraisonfrais_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listelivraisonfrais',
            name='etatFinal',
            field=models.CharField(choices=[('terminer', 'terminer'), ('en cours', 'en cours'), ('enpanne', 'enpanne')], default='en cours', max_length=300),
        ),
        migrations.AddField(
            model_name='listelivraisonsec',
            name='etatFinal',
            field=models.CharField(choices=[('terminer', 'terminer'), ('en cours', 'en cours'), ('enpanne', 'enpanne')], default='en cours', max_length=300),
        ),
        migrations.AlterField(
            model_name='listelivraisonfrais',
            name='etat',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('-1', '-1')], default='-1', max_length=300),
        ),
        migrations.AlterField(
            model_name='listelivraisonsec',
            name='etat',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('-1', '-1')], default='-1', max_length=300),
        ),
    ]
